---
title: Waar is het ruimtestation?
hero_image: images/banner.png
description: Zoek de exacte locatie van het ISS
listed: true
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Wie is er in de ruimte?
  - 
    title: 'Uitdaging: laat het ruimtestation zien'
  - 
    title: Waar is het ISS?
  - 
    title: Het ISS op een kaart tekenen
  - 
    title: Wanneer zal het ISS recht boven je zijn?
  - 
    title: 'Uitdaging: vind meer overvliegtijden'
