---
title: Waar is het ruimtestation?
hero_image: images/banner.png
description: Zoek de exacte locatie van het ISS
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Wie is er in de ruimte?
  - 
    title: 'Uitdaging: laat het ruimtestation zien'
    completion:
      - engaged
  - 
    title: Waar is het ISS?
  - 
    title: Het ISS op een kaart tekenen
  - 
    title: Add data to your map
    completion:
      - internal
