---
title: Waar is het ruimtestation?
hero_image: images / banner.png
description: Zet de exacte locatie van het ISS uit.
theme: blauw
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: maker, ontwerp-0, programmeren-0, phys-comp-0, productie-0, community-0
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: ruimte
technologies: Python
site_areas: codeclub, python
steps:
  - 
    title: Invoering
  - 
    title: Wat je nodig zult hebben
  - 
    title: Wie zit er in de ruimte?
  - 
    title: 'Uitdaging: Laat het ambacht zien'
  - 
    title: Waar is het ISS?
  - 
    title: Het ISS op een kaart uitzetten
  - 
    title: Wanneer zal het ISS overhead zijn?
  - 
    title: 'Uitdaging: vind meer paasuurtjes'

