title: Where is the Space Station?
hero_image: images/banner.png
description: Find the exact location of the ISS
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: space
technologies: python
site_areas: codeclub, python
steps:
- title: Introduction
- title: What you will need
- title: Who is in space?
- title: 'Challenge: show the craft'
- title: Where is the ISS?
- title: Plotting the ISS on a map
- title: When will the ISS be overhead?
- title: 'Challenge: Find more pass-over times'

