---
title: Where is the Space Station?
hero_image: images/banner.png
description: Find the exact location of the ISS
listed: true
copyedit: false
version: 3.1.0
last_tested: 2025-01-03
steps:
- title: What you will make
- title: Who is in space?
  completion:
  - engaged
- title: Where is the ISS?
- title: Plot the ISS on a map
- title: Add data to your map
  completion:
  - internal
- title: Challenge
  challenge: true
- title: What can you do now?
  completion:
  - external
