---
title: अन्तरिक्ष स्टेशन कहाँ है?
hero_image: छवियों /बैनर.png
description: ISS का सटीक स्थान ज्ञात करें
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: परिचय
  - 
    title: आपको क्या आवश्यकता होगी
  - 
    title: अंतरिक्ष में कौन है?
  - 
    title: 'चुनौती: शिल्प दिखाओ'
  - 
    title: ISS कहां है?
  - 
    title: ISS को एक मानचित्र पर चिन्हित करना
  - 
    title: आईएसएस ऊपर कब होगा?
  - 
    title: 'चुनौती: खोजें अधिक समय जो बीत गया'
