---
title: अन्तरिक्ष स्टेशन कहाँ है?
hero_image: images/where-is-the-space-station.png
description: ISS के बिल्कुल सटीक स्थान पता लगाएँ।
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: भूमिका
  - 
    title: अन्तरिक्ष में कौन है?
  - 
    title: 'चुनौती: क्राफ्ट दिखाएँ'
  - 
    title: 'ISS कहाँ है?'
  - 
    title: ISS सिर के ऊपर से कब गुजरेगा?
  - 
    title: 'चुनौती: पासओवर के और समय ढूँढ़ें'
  - 
    title: When will the ISS be overhead?
  - 
    title: 'Challenge: find more pass-over times'
