---
title: 宇宙ステーションはどこですか？
hero_image: images/banner.png
description: ISSの正確な場所を見つける
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: 誰が宇宙にいるのか？
  - 
    title: 'チャレンジ：宇宙飛行士が乗っている宇宙ステーションの名前を表示しよう'
    completion:
      - engaged
  - 
    title: ISSはどこですか？
  - 
    title: マップにISSの位置をプロットする
  - 
    title: Add data to your map
    completion:
      - internal
