---
title: Onde fica a estação espacial?
hero_image: images / banner.png
description: Encontre a localização exata da ISS
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Introdução
  - 
    title: O que você precisará
  - 
    title: Quem está no espaço?
  - 
    title: 'Desafio: mostre o ofício'
  - 
    title: Onde fica a ISS?
  - 
    title: Plotando o ISS em um mapa
  - 
    title: Quando a ISS será sobrecarga?
  - 
    title: 'Desafio: encontre mais tempos de repercussão'
