---
title: 国际空间站在哪里？
hero_image: images/banner.png
description: 绘制 ISS 的准确位置。
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - title: 简介
  - title: 你需要哪些准备
  - title: 谁在太空中？
  - title: '挑战：展示国际空间站的位置'
  - title: 国际空间站在哪里？
  - title: 在地图上描出代表国际空间站的点
  - title: 国际空间站什么时候会从我们头顶飞过呢？
  - title: '挑战：找到更多从头顶飞过的时间'
