---
title: Gdje je svemirska postaja?
hero_image: images/banner.png
description: U ovom projektu koristit ćeš web uslugu kako bi saznao gdje se trenutno nalazi Međunarodna svemirska postaja (ISS) i ucrtao njenu lokaciju na kartu.
listed: true
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Sretan rođendan
  - 
    title: Ono što će vam trebati
  - 
    title: Who is in space?
  - 
    title: 'Challenge: show the craft'
  - 
    title: Where is the ISS?
  - 
    title: Plotting the ISS on a map
  - 
    title: When will the ISS be overhead?
  - 
    title: 'Challenge: find more pass-over times'
