---
title: '¿Dónde está la Estación Espacial?'
hero_image: images/banner.png
description: Traza la ubicación exacta de la ISS
listed: true
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: 'Reto: Mostrar la nave'
  - 
    title: '¿Dónde está la ISS?'
  - 
    title: '¿Cuándo pasará por encima la ISS?'
  - 
    title: Trazando la ISS en un mapa
  - 
    title: '¿Cuándo la ISS estará por encima de su posición?'
  - 
    title: 'Desafío: encontrar más horas cuando pasará por encima'
