title: Wo ist die Weltraumstation?
hero_image: images/banner.png
description: Zeichne die genaue Position der Internationalen Weltraumstation ISS auf
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: space
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Einführung
- title: Wer ist im Weltall?
- title: 'Aufgabe: Die Weltraumstation anzeigen'
- title: Wo ist die ISS?
- title: Wann wird die ISS über uns sein?
- title: 'Aufgabe: Finde noch mehr Überflugszeiten'