---
title: Wo ist die Weltraumstation?
hero_image: images/banner.png
description: Zeichne die genaue Position der Internationalen Weltraumstation ISS auf
listed: true
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - title: Einleitung
  - title: Was du brauchen wirst
  - title: Wer ist im Weltraum?
  - title: 'Aufgabe: Die Weltraumstation anzeigen'
  - title: Wo ist die ISS?
  - title: Zeichne die ISS auf einer Karte
  - title: Wann wird die ISS über dir sein?
  - title: 'Aufgabe: Finde mehr Überflugzeiten'
