---
title: Wo ist die Weltraumstation?
hero_image: images/banner.png
description: Zeichne die genaue Position der Internationalen Weltraumstation ISS auf
listed: true
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - title: Einleitung
  - title: Was du brauchen wirst
  - title: 'Aufgabe: Die Weltraumstation anzeigen'
  - title: 'Wo ist die ISS?'
  - title: Wo befindet sich die ISS?
  - title: 'Aufgabe: Finde noch mehr Überflugszeiten'
  - title: Wann wird die ISS über dir sein?
  - title: 'Herausforderung: finde mehr Zeiten wenn sie sich über dir befindet'
