---
title: Unde este Stația Spațială?
hero_image: images/banner.png
description: Găsiți locația exactă a Stației Spațiale Internaționale
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Introducere
  - 
    title: De ce vei avea nevoie
  - 
    title: Cine este în spațiu?
  - 
    title: 'Provocare: arată meseria'
  - 
    title: Unde este Stația Spațială Internațională?
  - 
    title: Reprezentarea Stației Spațiale Internaționale pe o hartă
  - 
    title: When will the ISS be overhead?
  - 
    title: 'Challenge: find more pass-over times'
