---
title: Unde este Stația Spațială?
hero_image: images/banner.png
description: Găsiți locația exactă a Stației Spațiale Internaționale
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Introducere
  - 
    title: De ce vei avea nevoie
  - 
    title: Cine este în spațiu?
  - 
    title: 'Provocare: arată meseria'
  - 
    title: Unde este SSI?
  - 
    title: Reprezentarea SSI pe o hartă
  - 
    title: Când va fi SSI deasupra?
  - 
    title: 'Provocare: găsiți mai multe perioade de trecere pe deasupra SSI'
