---
title: Onde fica a estação espacial?
hero_image: images / banner.png
description: Encontre a localização exata da ISS
theme: azul
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programação-3, phys-comp-0, fabricação-0, comunidade-0
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: espaço
technologies: python
site_areas: projetos
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você precisará
  - 
    title: Quem está no espaço?
  - 
    title: 'Desafio: mostre o ofício'
  - 
    title: Onde fica a ISS?
  - 
    title: Plotando o ISS em um mapa
  - 
    title: Quando a ISS será sobrecarga?
  - 
    title: 'Desafio: encontre mais tempos de repercussão'
