---
title: Onde está a estação espacial?
hero_image: images/banner.png
description: Encontre a localização exata da ISS
listed: true
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você precisará
  - 
    title: Quem está no espaço?
  - 
    title: 'Desafio: Mostre a nave'
  - 
    title: Onde está a ISS?
  - 
    title: Plotando a ISS em um mapa
  - 
    title: Quando a ISS estará logo acima?
  - 
    title: 'Desafio: Encontre mais tempos de passagem'
