---
title: أين محطة الفضاء الدولية؟
hero_image: images/where-is-the-space-station.png
description: حدِّد الموقع الدقيق لمحطة الفضاء الدولية.
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-22-01
steps:
  - 
    title: المقدمة
  - 
    title: ما ستحتاج إليه
  - 
    title: من في الفضاء؟
  - 
    title: 'التحدي: عرض الحرفة'
  - 
    title: أين هي محطة الفضاء الدولية؟
  - 
    title: التخطيط لمحطة الفضاء الدولية على الخريطة
  - 
    title: متى ستكون المحطة الفضائية الدولية ؟
  - 
    title: 'التحدي: العثور على مزيد من مرات التمرير'
