hero_image: images/where-is-the-space-station.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: أين محطة الفضاء الدولية؟
description: حدِّد الموقع الدقيق لمحطة الفضاء الدولية.
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: space
technologies: python
site_areas: codeclub, python
steps:
- title: المقدمة
- title: من الموجودون في الفضاء؟
- title: 'التحدي: اعرض المركبة الفضائية'
- title: أين توجد محطة الفضاء الدولية؟
- title: متى ستكون محطة الفضاء الدولية فوق موقع معين مباشرة؟
- title: 'التحدي: ابحث عن أوقات أخرى لمرور المحطة فوق موقع معين مباشرة'

