---
title: أين محطة الفضاء الدولية؟
hero_image: images/banner.png
description: حدِّد الموقع الدقيق لمحطة الفضاء الدولية.
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: المقدمة
  - 
    title: ما ستحتاج إليه
  - 
    title: من في الفضاء؟
  - 
    title: 'التحدي: عرض الحرفة'
    completion:
      - engaged
  - 
    title: أين هي محطة الفضاء الدولية؟
  - 
    title: رسم محطة الفضاء الدولية على الخريطة
  - 
    title: Add data to your map
    completion:
      - internal
