---
title: أين محطة الفضاء الدولية؟
hero_image: images/where-is-the-space-station.png
description: حدِّد الموقع الدقيق لمحطة الفضاء الدولية.
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-22-01
steps:
  - 
    title: المقدمة
  - 
    title: من الموجودون في الفضاء؟
  - 
    title: 'التحدي: اعرض المركبة الفضائية'
  - 
    title: 'أين توجد محطة الفضاء الدولية؟'
  - 
    title: متى ستكون محطة الفضاء الدولية فوق موقع معين مباشرة؟
  - 
    title: 'التحدي: ابحث عن أوقات أخرى لمرور المحطة فوق موقع معين مباشرة'
  - 
    title: When will the ISS be overhead?
  - 
    title: 'Challenge: find more pass-over times'
