---
title: Gdzie jest Stacja Kosmiczna?
hero_image: images / banner.png
description: Find the exact location of the ISS
theme: niebieski
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: przestrzeń
technologies: pyton
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Co będzie potrzebne
  - 
    title: Kto jest w kosmosie?
  - 
    title: 'Challenge: show the craft'
  - 
    title: Gdzie jest ISS?
  - 
    title: Drukowanie ISS na mapie
  - 
    title: Kiedy ISS będzie nad głową?
  - 
    title: 'Challenge: find more pass-over times'
