---
title: Gdzie jest Stacja Kosmiczna?
hero_image: images/banner.png
description: Znajdź dokładną lokalizację Międzynarodowej Stacji Kosmicznej (ISS)
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Wprowadzenie
  - 
    title: Co będzie potrzebne
  - 
    title: Kto jest w kosmosie?
  - 
    title: 'Wyzwanie: pokaż pojazd'
  - 
    title: Gdzie jest ISS?
  - 
    title: Nanoszenie ISS na mapę
  - 
    title: Kiedy ISS będzie nad głową?
  - 
    title: 'Wyzwanie: znajdź więcej czasów przejścia'
