---
title: Gdzie jest Stacja Kosmiczna?
hero_image: images / banner.png
description: Znajdź dokładną lokalizację Międzynarodowej Stacji Kosmicznej (ISS)
theme: niebieski
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: kosmos
technologies: python
site_areas: projekty
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: '#wprowadzenie'
  - 
    title: Co będziesz potrzebować
  - 
    title: Kto jest w kosmosie?
  - 
    title: 'Wyzwanie: pokaż pojazd'
  - 
    title: Gdzie jest ISS?
  - 
    title: Nanoszenie ISS na mapę
  - 
    title: Kiedy ISS będzie nad głową?
  - 
    title: 'Wyzwanie: znajdź więcej czasów przejścia'
