---
title: Gdzie jest Stacja Kosmiczna?
hero_image: images / banner.png
description: Narysuj dokładną lokalizację ISS.
theme: niebieski
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: twórca, design-0, programowanie-0, phys-comp-0, production-0, community-0
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: przestrzeń
technologies: pyton
site_areas: codeclub, python
steps:
  - 
    title: Wprowadzenie
  - 
    title: Co będzie potrzebne
  - 
    title: Kto jest w kosmosie?
  - 
    title: 'Wyzwanie: Pokaż statek'
  - 
    title: Gdzie jest ISS?
  - 
    title: Drukowanie ISS na mapie
  - 
    title: Kiedy ISS będzie nad głową?
  - 
    title: 'Wyzwanie: Znajdź więcej czasu paschalnego'

