---
title: Gdje je svemirska stanica?
hero_image: images/banner.png
description: Nađi tačnu lokaciju Međunarodne svemirske stanice (ISS)
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Ko je u svemiru?
  - 
    title: 'Izazov: prikaži letjelicu'
  - 
    title: Gdje se nalazi ISS?
  - 
    title: Ucrtavanje ISS na kartu
  - 
    title: Kada će ISS biti iznad nas?
  - 
    title: 'Izazov: pronađi još vremena prolaska'
