---
title: Où est la Station Spatiale ?
hero_image: images/banner.png
description: Trouver l'emplacement exact de l'ISS
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - title: Introduction
  - title: Ce dont tu auras besoin
  - title: Qui est dans l'espace ?
  - title: 'Défi : montrer la fabrication'
  - title: Où est l'ISS?
  - title: Tracer l'ISS sur une carte
  - title: Quand l'ISS sera-t-il au-dessus?
  - title: 'Défi : trouver plus de temps de passage'
