---
title: Dov'è la Stazione Spaziale?
hero_image: images/banner.png
description: Traccia la posizione esatta della ISS
listed: true
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Chi è nello Spazio?
  - 
    title: 'Sfida: Mostra il Veicolo'
  - 
    title: 'Dov''è la ISS?'
  - 
    title: Quando sarà la ISS in alto?
  - 
    title: 'Sfida: Trova altri orari di passaggio'
  - 
    title: When will the ISS be overhead?
  - 
    title: 'Challenge: find more pass-over times'
