---
title: Uzay İstasyonu nerede?
hero_image: images/banner.png
description: ISS'nin tam konumunu bulun
listed: true
copyedit: false
version: 3.1.0
last_tested: 2018-11-22
steps:
  - title: Giriş
  - title: Nelere ihtiyacınız olacak
  - title: Uzayda kim var?
  - title: "Meydan okuma: aracı göster"
    completion:
      - engaged
  - title: ISS nerede?
  - title: ISS'i harita üzerinde gösterme
  - title: "ISS ne zaman üstümüzde olacak?"
    completion:
      - internal
  - title: "Meydan okuma: daha fazla geçiş süresi bulun"
